name: palindrome_numbers
author: rchavarria
description: A program writen in Dart to compute those numbers that follow 102 + 201 = 303
homepage: http://rchavarria.github.io
dev_dependencies:
    unittest: '>=0.10.0'

