name: Differences game
description: Three people launch a coin. They can get heads or tails. Win the person who gets the different side. The game is a draw if all people get heads, or get tails at the same time.

  
