name: stone_paper_scissors
author: rchavarria
description: A program writen in Dart to play the game "Stone, Paper, Scissors"
homepage: http://rchavarria.github.io
dev_dependencies:
    unittest: '>=0.10.0'

